#!/usr/bin/env python3
"""Convert an X11 misc-fixed PCF font into the embedded glyph table ssp/render/font_6x13.inc.

The misc-fixed fonts are public domain. Usage:
    python3 tools/gen_font.py /usr/share/fonts/X11/misc/6x13.pcf.gz > ssp/render/font_6x13.inc
"""
import gzip
import struct
import sys

PCF_ACCELERATORS, PCF_METRICS, PCF_BITMAPS, PCF_BDF_ENCODINGS = 1 << 1, 1 << 2, 1 << 3, 1 << 5
CELL_W, CELL_H, FIRST, LAST = 6, 13, 32, 126


def main(path):
    data = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    assert data[:4] == b"\x01fcp", "not a PCF file"
    (count,) = struct.unpack_from("<i", data, 4)
    toc = {}
    for i in range(count):
        typ, fmt, size, off = struct.unpack_from("<iiii", data, 8 + 16 * i)
        toc[typ] = off

    def table(typ):
        off = toc[typ]
        (fmt,) = struct.unpack_from("<i", data, off)
        return off + 4, fmt, (">" if fmt & 4 else "<")

    # Font ascent from the accelerator table.
    off, fmt, e = table(PCF_ACCELERATORS)
    font_ascent, _ = struct.unpack_from(e + "ii", data, off + 8)

    # Per-glyph metrics.
    off, fmt, e = table(PCF_METRICS)
    metrics = []
    if fmt & 0x100:  # compressed
        (n,) = struct.unpack_from(e + "h", data, off)
        for i in range(n):
            lb, rb, w, asc, desc = (b - 0x80 for b in data[off + 2 + 5 * i: off + 7 + 5 * i])
            metrics.append((lb, rb, asc, desc))
    else:
        (n,) = struct.unpack_from(e + "i", data, off)
        for i in range(n):
            lb, rb, w, asc, desc, _ = struct.unpack_from(e + "hhhhhH", data, off + 4 + 12 * i)
            metrics.append((lb, rb, asc, desc))

    # Glyph bitmaps.
    off, fmt, e = table(PCF_BITMAPS)
    (n,) = struct.unpack_from(e + "i", data, off)
    offsets = struct.unpack_from(e + "%di" % n, data, off + 4)
    bits = off + 4 + 4 * n + 16
    pad = 1 << (fmt & 3)
    msbit = bool(fmt & 8)

    # Encoding → glyph index.
    off, fmt, e = table(PCF_BDF_ENCODINGS)
    min2, max2, min1, max1, _ = struct.unpack_from(e + "hhhhh", data, off)
    assert min1 == 0 and min2 <= FIRST and max2 >= LAST, "ASCII range not covered"

    def glyph_index(ch):  # ASCII lives in row byte1 == 0
        (g,) = struct.unpack_from(e + "H", data, off + 10 + 2 * (ch - min2))
        return None if g == 0xFFFF else g

    print("// Generated by tools/gen_font.py from X11 misc-fixed 6x13 (public domain). Do not edit.")
    print("// One entry per ASCII code %d..%d; each row's low %d bits are pixels, bit %d = leftmost." %
          (FIRST, LAST, CELL_W, CELL_W - 1))
    for ch in range(FIRST, LAST + 1):
        rows = [0] * CELL_H
        g = glyph_index(ch)
        if g is not None:
            lb, rb, asc, desc = metrics[g]
            w = rb - lb
            stride = ((w + 7) // 8 + pad - 1) // pad * pad
            for r in range(asc + desc):
                y = font_ascent - asc + r
                if not 0 <= y < CELL_H:
                    continue
                for x in range(w):
                    byte = data[bits + offsets[g] + r * stride + x // 8]
                    on = (byte >> (7 - x % 8)) & 1 if msbit else (byte >> (x % 8)) & 1
                    cx = lb + x
                    if on and 0 <= cx < CELL_W:
                        rows[y] |= 1 << (CELL_W - 1 - cx)
        print("{%s},  // %r" % (",".join("0x%02x" % v for v in rows), chr(ch)))


if __name__ == "__main__":
    main(sys.argv[1])
