#!/usr/bin/env python3
"""Extract SigPlot/XMidas colormaps from sigplot's js/m.js into ssp/render/colormaps.inc.

    python3 tools/gen_colormaps.py ../sigplot/js/m.js > ssp/render/colormaps.inc
"""
import re
import sys

WANTED = ["Greyscale", "Ramp Colormap", "Color Wheel", "Spectrum", "calewhite", "HotDesat",
          "Sunset", "Hot", "Cold"]

src = open(sys.argv[1]).read()
body = src[src.index("colormap: ["):]
entries = {}
for m in re.finditer(r'name:\s*"([^"]+)",\s*colors:\s*\[(.*?)\]\s*(?:\.reverse\(\))?\s*\}', body, re.S):
    name, colors = m.group(1), m.group(2)
    stops = []
    points = re.findall(r"pos:\s*([\d.]+),\s*red:\s*([\d.]+),\s*green:\s*([\d.]+),\s*blue:\s*([\d.]+)", colors)
    if points:
        stops = [(float(p) / 100, float(r) / 100, float(g) / 100, float(b) / 100) for p, r, g, b in points]
    else:
        hexes = re.findall(r"#([0-9a-fA-F]{6})", colors)
        n = len(hexes)
        stops = [(i / (n - 1), int(h[0:2], 16) / 255, int(h[2:4], 16) / 255, int(h[4:6], 16) / 255)
                 for i, h in enumerate(hexes)]
    # XMidas tables pad to a fixed length with extra stops at 100; SigPlot stops at the first.
    for i, st in enumerate(stops):
        if st[0] >= 1.0:
            stops = stops[:i + 1]
            break
    entries[name] = stops

print("// Generated by tools/gen_colormaps.py from SigPlot js/m.js (Apache-2.0). Do not edit.")
print("// {name, {{pos, r, g, b}...}} with every value in [0, 1]; interpolate linearly.")
for name in WANTED:
    stops = entries[name]
    label = "Ramp" if name == "Ramp Colormap" else name
    print('{"%s", {%s}},' % (label, ", ".join("{%.4f, %.4f, %.4f, %.4f}" % s for s in stops)))
