name: Build wheels

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install cibuildwheel
      run: pip install cibuildwheel

    - name: Build wheels
      env:
        CIBW_BEFORE_BUILD_LINUX: yum install -y libX11-devel
        CIBW_LOG_LEVEL: DEBUG
      run: |
        cibuildwheel --output-dir dist
    
    - name: Check wheels
      run: |
        pip install twine
        twine check dist/*

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        pip install twine
        twine upload --verbose --repository testpypi dist/*